version: '3.8'

networks:
  app_network:

services:
  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app_network

  backend:
    build: ./products-server
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - app_network

volumes:
  db_data:
